title: Hello there!

remote_theme: pages-themes/minimal@v0.2.0 # minimal is the name of the theme
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

markdown_extensions:
  - attr_list

sass:
  sass_dir: _sass
  style: compressed
